import fs from "node:fs";
import path from "node:path";

// Code generation for the compiled standalone binary: enumerates the drizzle
// migrations folder and renders a TypeScript module that imports each
// migration's SQL (plus the migrator journal) as embedded text, so compiled
// binaries carry their migrations without `--asset` (a bun 1.4 feature).
//
// build.ts runs this on every compile; migrate.test.ts asserts the checked-in
// generated module matches this output.

export const GENERATED_MODULE_PATH = path.join(import.meta.dir, "migrations.generated.ts");

const DRIZZLE_DIR = path.join(import.meta.dir, "../../drizzle");

export function generateMigrationsModule(): string {
  const migrations = fs
    .readdirSync(DRIZZLE_DIR)
    .filter(file => file.endsWith(".sql"))
    .sort()
    .map(file => file.slice(0, -".sql".length));

  const imports = migrations.map(
    (name, index) =>
      `import migration${index} from "../../drizzle/${name}.sql" with { type: "text" };`,
  );

  const entries = migrations.map(
    (name, index) => `    { name: ${JSON.stringify(name)}, sql: migration${index} },`,
  );

  return `// Generated by build.ts — do not edit by hand. Regenerate with \`bun build.ts\`.
${imports.join("\n")}
import journalJson from "../../drizzle/meta/_journal.json" with { type: "json" };

export const EMBEDDED_MIGRATIONS = {
  journal: JSON.stringify(journalJson),
  migrations: [
${entries.join("\n")}
  ],
};
`;
}

export function writeMigrationsModule(): boolean {
  const next = generateMigrationsModule();
  const current = fs.existsSync(GENERATED_MODULE_PATH)
    ? fs.readFileSync(GENERATED_MODULE_PATH, "utf-8")
    : null;
  if (current === next) return false;
  fs.writeFileSync(GENERATED_MODULE_PATH, next);
  return true;
}
