// Generated by build.ts — do not edit by hand. Regenerate with `bun build.ts`.
import migration0 from "../../drizzle/0000_mean_magdalene.sql" with { type: "text" };
import migration1 from "../../drizzle/0001_icy_husk.sql" with { type: "text" };
import migration2 from "../../drizzle/0002_silver_circuit.sql" with { type: "text" };
import migration3 from "../../drizzle/0003_tree_node_triggers.sql" with { type: "text" };
import migration4 from "../../drizzle/0004_tree_nodes_tree_id_index.sql" with { type: "text" };
import migration5 from "../../drizzle/0005_clean_red_shift.sql" with { type: "text" };
import migration6 from "../../drizzle/0006_history_item_model_json.sql" with { type: "text" };
import journalJson from "../../drizzle/meta/_journal.json" with { type: "json" };

export const EMBEDDED_MIGRATIONS = {
  journal: JSON.stringify(journalJson),
  migrations: [
    { name: "0000_mean_magdalene", sql: migration0 },
    { name: "0001_icy_husk", sql: migration1 },
    { name: "0002_silver_circuit", sql: migration2 },
    { name: "0003_tree_node_triggers", sql: migration3 },
    { name: "0004_tree_nodes_tree_id_index", sql: migration4 },
    { name: "0005_clean_red_shift", sql: migration5 },
    { name: "0006_history_item_model_json", sql: migration6 },
  ],
};
