import { t } from "structural";
import type { Transport } from "../transports/transport-common.ts";
import type { Result } from "../result.ts";
import type { Content } from "./llm-ir.ts";

/*
 * Tool definitions
 * -------------------------------------------------------------------------------------------------
 *
 * Tools have to define a few things:
 *
 * 1. A tool name.
 * 2. A schema for their input arguments from the LLM
 * 3. A schema that we parse the input into. If we don't need parse the LLM input, this can be
 *    autogenerated.
 * 4. A parse function that parses the input into the parsed form. If we don't need to parse the LLM
 *    input, this can be autogenerated.
 * 5. A validate function that validates the parsed data at runtime, e.g. "does this file still have
 *    this search string even though we performed two edits previously on it"
 * 6. A run function, which takes the tool data and runs it, returning some result
 */
export type ToolDef<
  Data,
  Name extends string,
  Arguments,
  Parsed,
  SubagentNames extends string,
  Extra,
> = {
  name: Name;
  ArgumentsSchema: t.Type<Arguments>;
  ParsedSchema: t.Type<Parsed>;
  parse: (
    args: ToolParseArgs<Arguments>,
  ) => Promise<Result<ParseResult<Arguments, Parsed>, string>>;
  validate: (
    abortSignal: AbortSignal,
    transport: Transport,
    t: {
      original: Schema<Name, Arguments>;
      parsed: Schema<Name, Parsed>;
    },
    data: Data,
  ) => Promise<Result<null, string>>;
  run: (
    args: ToolRunArgs<Data, Name, Arguments, Parsed>,
  ) => Promise<Result<ToolReturn<SubagentNames, Extra>, string>>;
};

export type ToolParseArgs<Arguments> = {
  signal: AbortSignal;
  transport: Transport;
  original: Arguments;
};

export type ToolRunArgs<Data, Name extends string, Arguments, Parsed> = {
  signal: AbortSignal;
  transport: Transport;
  toolCall: {
    original: Schema<Name, Arguments>;
    parsed: Schema<Name, Parsed>;
  };
  data: Data;
};

export type ParseResult<Arguments, Parsed> = {
  original: Arguments;
  parsed: Parsed;
};

/*
 * Basic schema for tool calling
 */
type Schema<Name extends string, Arguments> = {
  name: Name;
  arguments: Arguments;
};

/*
 * Tools can return:
 *
 * - output content
 * - subagent invocations (for their subagent dependencies)
 * - any custom LLM IR defined
 */
export type ToolReturn<SubagentName extends string, Extra> =
  | (Content & {
      type: "output";

      // The line count to show in the UI, if it's not just the number of lines in the content
      lines?: number;
    })
  | {
      type: "invoke-subagent";
      name: SubagentName;
    }
  | {
      type: "custom-ir";
      data: Extra;
    };

type RawToolFactory<
  Data,
  S extends Schema<any, any>,
  Parsed,
  SubagentNames extends string,
  Extra,
> = (args: {
  signal: AbortSignal;
  transport: Transport;
  data: Data;
}) => Promise<ToolDef<Data, S["name"], S["arguments"], Parsed, SubagentNames, Extra> | null>;

type SimpleRawToolFactory<
  Data,
  S extends Schema<any, any>,
  Parsed,
  SubagentNames extends string,
  Extra,
> = (args: {
  signal: AbortSignal;
  transport: Transport;
  data: Data;
}) => Promise<
  | (Omit<
      ToolDef<Data, S["name"], S["arguments"], Parsed, SubagentNames, Extra>,
      "ArgumentsSchema" | "ParsedSchema" | "name" | "validate"
    > &
      Partial<
        Pick<ToolDef<Data, S["name"], S["arguments"], Parsed, SubagentNames, Extra>, "validate">
      >)
  | null
>;

type SimpleAutoParsedRawToolFactory<
  Data,
  S extends Schema<any, any>,
  SubagentNames extends string,
  Extra,
> = (args: {
  signal: AbortSignal;
  transport: Transport;
  data: Data;
}) => Promise<
  | (Omit<
      ToolDef<Data, S["name"], S["arguments"], S["arguments"], SubagentNames, Extra>,
      "ArgumentsSchema" | "ParsedSchema" | "name" | "parse" | "validate"
    > &
      Partial<
        Pick<
          ToolDef<Data, S["name"], S["arguments"], S["arguments"], SubagentNames, Extra>,
          "validate"
        >
      >)
  | null
>;

type ToolFactoryArgs<Data> = {
  signal: AbortSignal;
  transport: Transport;
  data: Data;
};

type DynamicToolFactoryReturn<T extends (...args: any) => any> = ReturnType<
  Extract<Exclude<Awaited<ReturnType<T>>, null>, (...args: any) => any>
>;

type DynamicToolFactorySubagents<T extends (...args: any) => any> = ToolSubagentNames<
  Exclude<Awaited<ReturnType<T>>, null>
>;

type RuntimeToolDefinition<Extra> = Omit<
  ToolDef<unknown, string, unknown, unknown, string, Extra>,
  "ArgumentsSchema" | "ParsedSchema" | "name" | "parse" | "validate"
> &
  Partial<Pick<ToolDef<unknown, string, unknown, unknown, string, Extra>, "parse" | "validate">>;

// Public tool factories are the precise raw factory type plus the capability brand. Keeping the raw
// factory in the intersection preserves literal tool names and parsed argument types.
export type ToolFactory<
  Data,
  S extends Schema<any, any>,
  Parsed,
  SubagentNames extends string,
  Extra,
> = RawToolFactory<Data, S, Parsed, SubagentNames, Extra> &
  ToolFactoryRequirements<SubagentNames, Extra>;

export class ToolBuilder<Extra = never, Data = unknown> {
  withIR<NewExtra>(): ToolBuilder<NewExtra, Data> {
    return new ToolBuilder<NewExtra, Data>();
  }

  withData<NewData>(): ToolBuilder<Extra, NewData> {
    return new ToolBuilder<Extra, NewData>();
  }

  /*
   * Caller-facing static tool builder, explicit parse form.
   *
   * Use this when the LLM's raw arguments are not the shape the tool wants to run with. The caller
   * supplies both schemas up front, then define(...) must supply parse({ original, ... }) to produce ParsedSchema.
   * Example: read({ path }) parses into { path, originalFileContents }.
   *
   * The return type is intentionally precise: the resulting tool remembers its name, raw args,
   * parsed args, subagent dependencies, and this builder's Extra IR type.
   */
  declare<
    Name extends string,
    Arguments,
    Parsed,
    const SubagentNames extends string = never,
  >(partial: {
    name: Name;
    ArgumentsSchema: t.Type<Arguments>;
    ParsedSchema: t.Type<Parsed>;
    subagents?: readonly SubagentNames[];
  }): {
    define: <
      T extends SimpleRawToolFactory<Data, Schema<Name, Arguments>, Parsed, SubagentNames, Extra>,
    >(
      factory: (args: Parameters<T>[0]) => Promise<Awaited<ReturnType<T>>>,
    ) => RawToolFactory<Data, Schema<Name, Arguments>, Parsed, SubagentNames, Extra> &
      ToolFactoryRequirements<SubagentNames, Extra>;
  };

  /*
   * Caller-facing static tool builder, auto-parse form.
   *
   * Use this for the common case where the LLM's raw arguments are already the shape the tool runs
   * with. The caller omits ParsedSchema and parse(...). The resulting tool behaves as if
   * ParsedSchema === ArgumentsSchema and parse(...) returned { original: x, parsed: x }.
   *
   * Subagent inference still works here: subagents: ["view"] records "view"; omitting subagents
   * records never.
   */
  declare<Name extends string, Arguments, const SubagentNames extends string = never>(partial: {
    name: Name;
    ArgumentsSchema: t.Type<Arguments>;
    ParsedSchema?: undefined;
    subagents?: readonly SubagentNames[];
  }): {
    define: <
      T extends SimpleAutoParsedRawToolFactory<Data, Schema<Name, Arguments>, SubagentNames, Extra>,
    >(
      factory: (args: Parameters<T>[0]) => Promise<Awaited<ReturnType<T>>>,
    ) => RawToolFactory<Data, Schema<Name, Arguments>, Arguments, SubagentNames, Extra> &
      ToolFactoryRequirements<SubagentNames, Extra>;
  };

  /*
   * Implementation shared by both static builder forms.
   *
   * From the caller's perspective, declare(...).define(...) returns a load-time factory. At runtime we
   * call the caller's factory, then attach the metadata owned by declare(...): the public name, the raw
   * schema, the parsed schema, and the generated parser when no custom parser was supplied.
   *
   * The overload signatures above provide the precise API. This body deliberately works with a
   * looser runtime shape, then casts once at the boundary to attach the compile-time-only brand.
   */
  declare(partial: {
    name: string;
    ArgumentsSchema: t.Type<any>;
    ParsedSchema?: t.Type<any>;
    subagents?: readonly string[];
  }): any {
    return {
      define: (
        factory: (args: ToolFactoryArgs<Data>) => Promise<RuntimeToolDefinition<Extra> | null>,
      ) => {
        const wrapped = async (args: ToolFactoryArgs<Data>) => {
          const def = await factory(args);
          if (def === null) return null;

          return {
            ...def,
            name: partial.name,
            ArgumentsSchema: partial.ArgumentsSchema,
            ParsedSchema: partial.ParsedSchema ?? partial.ArgumentsSchema,
            parse:
              def.parse ??
              (async ({ original }) => ({
                success: true as const,
                data: {
                  original,
                  parsed: original,
                },
              })),
            validate: def.validate ?? (async () => ({ success: true, data: null })),
          };
        };

        // The brand has no runtime representation; it only makes defineIR reject tools whose custom
        // IR output is not included in the target IR universe.
        return wrapped as unknown as ToolFactory<
          Data,
          Schema<string, unknown>,
          unknown,
          string,
          Extra
        >;
      },
    };
  }

  /*
   * Caller-facing dynamic tool builder.
   *
   * Use this when the exact tool shape is not known until load time, for example when the schema
   * depends on data, transport capabilities, or discovered project state. The caller returns a
   * normal declare(...).define(...) result from the selector rather than repeating a second dynamic
   * API for name/schema/subagents/parse behavior.
   *
   * The selected tool carries the same type information as a static tool. This wrapper preserves
   * that information and forwards the runtime args into the selected factory.
   */
  dynamicDefineTool<
    T extends (
      args: ToolFactoryArgs<Data>,
    ) => Promise<ToolFactory<Data, any, any, any, Extra> | null>,
  >(
    factory: T,
  ): ((args: ToolFactoryArgs<Data>) => DynamicToolFactoryReturn<T>) &
    ToolFactoryRequirements<DynamicToolFactorySubagents<T>, Extra> {
    const selectTool = factory as unknown as (args: ToolFactoryArgs<Data>) => ReturnType<T>;

    const wrapped = async (args: ToolFactoryArgs<Data>) => {
      const selectedTool = await selectTool(args);
      const runSelectedTool = selectedTool as
        | null
        | ((args: ToolFactoryArgs<Data>) => DynamicToolFactoryReturn<T>);

      // One-level flatMap: the selector returns a tool factory; dynamicDefineTool must itself
      // behave like a tool factory that returns the selected tool definition.
      return runSelectedTool?.(args) ?? null;
    };

    // The brand has no runtime representation; it only makes defineIR reject tools whose custom
    // IR output is not included in the target IR universe.
    return wrapped as unknown as ((args: ToolFactoryArgs<Data>) => DynamicToolFactoryReturn<T>) &
      ToolFactoryRequirements<DynamicToolFactorySubagents<T>, Extra>;
  }
}

// A shared tool builder for callers that do not need a dedicated builder instance.
export const tools = new ToolBuilder();

export type ToolMap<SubagentNames extends string, Extra> = {
  [key: string]: ToolFactory<any, any, any, SubagentNames, Extra>;
};
export type LoadedTools<T extends ToolMap<any, any>> = {
  [K in keyof T]: Exclude<Awaited<ReturnType<T[K]>>, null>;
};
export type ToolCall<T extends ToolMap<any, any>> = {
  [K in keyof LoadedTools<T>]: {
    type: "tool-call";
    name: LoadedTools<T>[K]["name"];
    toolCallId: string;
    parsed: t.GetType<LoadedTools<T>[K]["ParsedSchema"]>;
    original: t.GetType<LoadedTools<T>[K]["ArgumentsSchema"]>;
  };
}[keyof LoadedTools<T>];

/*
 * ALERT ALERT
 *
 * Type system bullshit used for branding and validating IRs with respect to tools and subagent
 * dependencies.
 */

// Tool factories are structurally just functions, so TypeScript can otherwise forget which IR
// extension set they were created for if the implementation does not currently return custom IR.
// These unique-symbol fields are a compile-time-only brand attached by defineTool.
declare const toolFactoryExtra: unique symbol;
declare const toolFactorySubagents: unique symbol;

// The brand should be covariant: a base tool that emits no custom IR (never) is valid in a richer
// IR context, but a richer tool is not valid in a base IR context.
type Covariant<T> = () => T;

// Required phantom fields keep Extra and SubagentNames visible when checking assignability to a
// ToolMap. They are never read or written at runtime.
export type ToolFactoryRequirements<SubagentNames extends string, Extra> = {
  readonly [toolFactoryExtra]: Covariant<Extra>;
  readonly [toolFactorySubagents]: Covariant<SubagentNames>;
};

export type ToolSubagentNames<T> =
  T extends ToolFactoryRequirements<infer SubagentNames, any> ? SubagentNames : never;
